name: CI

on:
  push:
    branches: [main]

  pull_request:

  workflow_dispatch:

jobs:
  formatting:
    name: "Check Formatting"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format -o none --set-exit-if-changed lib/* test/*

  analysis:
    name: "Static Analysis"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run analysis
        run: dart analyze

  test:
    name: "Run Tests"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.9
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install full_coverage
        run: dart pub global activate full_coverage

      - name: Generate full coverage test
        run: dart pub global run full_coverage


      - name: Run tests
        run: dart run coverage:test_with_coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
